# Generated by Django 4.1.5 on 2023-03-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='', upload_to='portfolio/images'),
        ),
    ]
