# Generated by Django 4.1.5 on 2023-03-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_url_alter_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
